name: GitHub Actions DevOpsCours
on: [push]
jobs:
  DevOpsCourse-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: show uptime
        run: uptime
      - name: Where I am?
        run: pwd
Terraform-validate:
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: final_exam/terraform/vpc.tf
