name: GitHub Actions DevOpsCours
on: [push, pull_request]
jobs:
  GitHub-Actions-DevOpsCours:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: show uptime
        run: uptime
      - name: Where I am?
        run: pwd