---
on:
  - push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      #- name: terraform init
      #  uses: robertdebock/terraform-action@1.1.1
      #  with:
      #    action: init
      #    directory: ./final_exam/terraform
      - name: terraform validate
        uses: robertdebock/terraform-action@1.1.1
        with:
          action: validate
          directory: ./final_exam/terraform
